name: eds-lessons
channels:
  - conda-forge
dependencies:
  - papermill=1.0.1
  - pip=19.0.3

  # Core scientific python
  - python=3.6
  - pyqt=5.9.2
  - scikit-learn=0.21.2

  # extentions
  - autopep8=1.4.4

  # Geo stuff
  - basemap=1.2.0
  - cartopy
  - contextily=1.0
  - earthpy=0.6.8
  - folium=0.9.1
  - gdal
  - geocoder=1.38.1
  - geojson=2.4.1
  - geopandas=0.5.0
  - geopy=1.20.0
  - libgdal
  - libiconv=1.15
  - pyproj
  - pysal=2.0.0
  - rasterio
  - rasterstats
  - scikit-image=0.15.0
  - shapely=1.6.4

  # natural language processing
  - nltk=3.2.5
  - tweepy=3.5

  - pip:
      # Utilities
      - cenpy
      - climata
      - elevation
      - hydrofunctions
      - mapboxgl
      - nbclean
      - richdem
